# Inpired by https://github.com/osamaq/react-native-template/blob/master/template/fastlane/Fastfile

# -------------Android Build & Deploy-------------#
platform :android do
  desc "Build the production release AAB."
  lane :build_production do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: "bundleRelease", project_dir: 'android/')
  end
end

# -------------Icons & Versioning-------------#
desc 'Android: Increment versionCode and set versionName to package.json version.'
package = load_json(json_path: "./package.json")
private_lane :inc_ver_android do
  increment_version_code(
    gradle_file_path: "./android/app/build.gradle",
  )

  increment_version_name(
    gradle_file_path: "./android/app/build.gradle",
    version_name: package['version']
  )
end

desc 'iOS: Increment build number and set the version to package.json version.'
private_lane :inc_ver_ios do
  increment_build_number(
    xcodeproj: './ios/blockstackwallet.xcodeproj'
  )
  increment_version_number(
    xcodeproj: './ios/blockstackwallet.xcodeproj',
    version_number: package['version']
  )
end

desc 'Bump build numbers, and set the display version to match the package.json version.'
# private_lane :bump do
lane :bump do
  inc_ver_android
  inc_ver_ios
end
