# Inpired by https://github.com/osamaq/react-native-template/blob/master/template/fastlane/Fastfile

# -------------Android Build & Deploy-------------#
platform :android do
  desc "Build the production release AAB."
  lane :build_production do
    keystore_path = "android/app/app.keystore"
    keystore_password = ENV["ANDROID_KEYSTORE_PASSWORD"]
    key_alias = ENV["ANDROID_KEY_ALIAS"]
    key_password = ENV["ANDROID_KEY_PASSWORD"]

    gradle(task: "clean", project_dir: "android/")
    gradle(
      task: "bundleRelease",
      project_dir: "android/",
      properties: {
        "android.injected.signing.store.file" => keystore_path,
        "android.injected.signing.store.password" => keystore_password,
        "android.injected.signing.key.alias" => key_alias,
        "android.injected.signing.key.password" => key_password,
      }
    )
    # Generate universal APK from aab that can be installed on any android device
    bundletool(
      ks_path: keystore_path,
      ks_password: keystore_password,
      ks_key_alias: key_alias,
      ks_key_alias_password: key_password,
      bundletool_version: '1.2.0',
      aab_path: "android/app/build/outputs/bundle/release/app-release.aab",
      apk_output_path: "android/app/build/outputs/bundle/release/app-release.apk"
    )
  end
end

# -------------Icons & Versioning-------------#
desc 'Android: Increment versionCode and set versionName to package.json version.'
package = load_json(json_path: "./package.json")
private_lane :inc_ver_android do
  increment_version_code(
    gradle_file_path: "./android/app/build.gradle",
  )

  increment_version_name(
    gradle_file_path: "./android/app/build.gradle",
    version_name: package['version']
  )
end

desc 'iOS: Increment build number and set the version to package.json version.'
private_lane :inc_ver_ios do
  increment_build_number(
    xcodeproj: './ios/blockstackwallet.xcodeproj'
  )
  increment_version_number(
    xcodeproj: './ios/blockstackwallet.xcodeproj',
    version_number: package['version']
  )
end

desc 'Bump build numbers, and set the display version to match the package.json version.'
# private_lane :bump do
lane :bump do
  inc_ver_android
  inc_ver_ios
end
