default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    # upload_to_play_store
  end
end
